# Generated by Django 2.1.7 on 2019-04-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_myobject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyObject',
        ),
    ]
