# Generated by Django 2.1.7 on 2019-04-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20190404_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
