# Generated by Django 2.1.7 on 2019-04-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20190404_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcode',
            name='code',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
