# Generated by Django 2.1.7 on 2019-04-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_barcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
